import * as yup from 'yup';
import schemas from '@/utils/schemas';

export const schema = yup.object().shape({
  nome: schemas.nome(true),
  data_nascimento: schemas.data_nascimento(true),
  cpf: schemas.cpf(true),
  atuacao: schemas.atuacao(),
  cargo: schemas.cargo(),
  email: schemas.email(true),
  telefone: schemas.telefone(true, true),
  password: schemas.password(true),
  confirm_password: schemas.confirm_password(true),
  cnpj: schemas.cnpj(true),
  razao_social: schemas.razao_social(true),
  nome_fantasia: schemas.nome_fantasia(true),
  ramo_atividade: schemas.ramo_atividade(true),
  numero_funcionarios: schemas.numero_funcionarios(),
  descricao: schemas.descricao(true),
  empresa_telefone: schemas.telefone(true, true),
  empresa_email: schemas.email(true),
  site: schemas.site(),
  cep: schemas.cep(false, true),
  logradouro: schemas.logradouro(false, true),
  numero: schemas.numero(false, true),
  complemento: schemas.complemento(false, true),
  bairro: schemas.bairro(false, true),
  cidade: schemas.cidade(false, true),
  estado: schemas.estado(false, true),
});
